-- =============================================================================
-- SERVER & NETWORKING HARDWARE — Cluster Nodes
-- =============================================================================

-- 1. CISCO — The Compute Node
INSERT INTO items (
  title, description, price, rating, rating_count,
  asset_tag, serial_number, model_name, model_number, manufacturer,
  category_id, location_id, default_location_id, status, quantity,
  cpu_type, ram_amount, hard_drive_info, gpu, network_info, role, storage_detail,
  notes
) VALUES (
  'Cisco UCS C220 M5 — "Cisco" Compute Node',
  E'Stateless Calculation Engine.\n\nThis machine is designed to eliminate I/O latency entirely. By loading the dataset into a ~600GB RAM Disk, it executes the Viterbi and Baum-Welch algorithms in nanoseconds without waiting for hard drives. It is "stateless," meaning it relies on BigBrain for data persistence.',
  12500.00, 5.0, 1,
  'SRV-CISCO-001', 'FCH2138V1AB', 'UCS C220 M5', 'UCSC-C220-M5SX', 'Cisco',
  11, 7, 7, 'available', 1,
  '2x Intel Xeon Gold 6130 (32 Cores / 64 Threads @ 2.1 GHz)',
  '768 GB DDR4 ECC (24 x 32GB) — All slots filled',
  '228 GB SSD (SATA) — Boot Drive only',
  NULL,
  '4x 10G Base-T (Copper) → LACP Bond (40Gbps)',
  'Stateless Calculation Engine',
  E'Boot: 228 GB SSD (SATA)\nData Storage: None (Uses RAM Disk ~600GB)',
  'All 24 DIMM slots populated for maximum memory bandwidth. Data storage is entirely in RAM Disk. Relies on BigBrain for persistence.'
);

-- 2. BIGBRAIN — The Database Node
INSERT INTO items (
  title, description, price, rating, rating_count,
  asset_tag, serial_number, model_name, model_number, manufacturer,
  category_id, location_id, default_location_id, status, quantity,
  cpu_type, ram_amount, hard_drive_info, gpu, network_info, role, storage_detail,
  notes
) VALUES (
  'Dell PowerEdge R730xd — "BigBrain" Database Node',
  E'High-Frequency Transactional Database.\n\nOptimized for low latency and high throughput. The high-clock-speed CPUs (3.2GHz) handle complex queries quickly, while the dedicated 15k RPM log drives ensure that heavy write operations never block the main data array. It serves as the "Source of Truth" for the cluster.',
  18000.00, 5.0, 1,
  'SRV-BIGBRAIN-001', 'JNKF732', 'PowerEdge R730xd', 'R730xd-24Bay', 'Dell',
  11, 7, 7, 'available', 1,
  '2x Intel Xeon E5-2667 v4 (16 Cores / 32 Threads @ 3.2 GHz)',
  '128 GB DDR4 ECC (4 x 32GB)',
  '120 GB SSD (SATA) — Boot Drive in Slot 20',
  NULL,
  '2x 10G SFP+ (Fiber) → LACP Bond (20Gbps)',
  'High-Frequency Transactional Database',
  E'Boot: 120 GB SSD (SATA) Slot 20\nTier 1 (Logs): 4x 600GB 15k SAS RAID 10 → /var/lib/postgresql/wal\nTier 2 (Data): 16x 1.2TB 10k SAS RAID 10 → /var/lib/postgresql/data',
  '24-Bay chassis. Tier 1 WAL logs on dedicated 15k RPM spindles ensures writes never block the main data array. Source of Truth for the cluster.'
);

-- 3. HAL — The Inference Node
INSERT INTO items (
  title, description, price, rating, rating_count,
  asset_tag, serial_number, model_name, model_number, manufacturer,
  category_id, location_id, default_location_id, status, quantity,
  cpu_type, ram_amount, hard_drive_info, gpu, network_info, role, storage_detail,
  notes
) VALUES (
  'Custom Workstation — "Hal" Inference Node',
  E'Hybrid Pre-Processing & GPU Inference.\n\nA dual-purpose heavy lifter. It uses its massive 88-thread CPU count to "chunk," format, and normalize raw data in parallel. It then feeds these matrices to the RTX 5070 for hardware-accelerated deep learning inference, returning the results to Vault.',
  9500.00, 5.0, 1,
  'SRV-HAL-001', 'HAL-WS-2024', 'Custom Workstation / Server', 'CUSTOM-DUAL-E5', 'Custom Build',
  11, 7, 7, 'available', 1,
  '2x Intel Xeon E5-2699 v4 (44 Cores / 88 Threads @ 2.2 GHz)',
  '64 GB DDR4 ECC (2 x 32GB)',
  '2 TB SSD (SATA/NVMe)',
  'NVIDIA RTX 5070 (16 GB GDDR7)',
  '1x 10G SFP+ (Fiber)',
  'Hybrid Pre-Processing & GPU Inference',
  '2 TB SSD (SATA/NVMe)',
  '88 threads for parallel data chunking/normalization. GPU-accelerated deep learning inference via RTX 5070. Returns results to Vault.'
);

-- 4. VAULT — The Archive Node
INSERT INTO items (
  title, description, price, rating, rating_count,
  asset_tag, serial_number, model_name, model_number, manufacturer,
  category_id, location_id, default_location_id, status, quantity,
  cpu_type, ram_amount, hard_drive_info, gpu, network_info, role, storage_detail,
  notes
) VALUES (
  'ZFS Server — "Vault" Archive Node',
  E'Disaster Recovery & Long-Term Storage.\n\nThe safety net. It continuously ingests Write-Ahead Logs (WAL) from BigBrain for point-in-time recovery. It also serves as the final destination for the massive results files generated by Cisco and Hal, keeping the high-speed tiers free for active work.',
  6000.00, 5.0, 1,
  'SRV-VAULT-001', 'VAULT-ZFS-001', 'ZFS Server', 'ZFS-CUSTOM', 'Custom Build',
  11, 8, 8, 'available', 1,
  NULL, NULL,
  'Pool A: 24 TB (Main Backup) | Pool B: 16 TB (Archive)',
  NULL,
  '2x 10G SFP+ (Fiber) → LACP Bond (20Gbps)',
  'Disaster Recovery & Long-Term Storage',
  E'Storage Pool A: 24 TB (Main Backup)\nStorage Pool B: 16 TB (Archive)\nZFS filesystem with snapshots',
  'Continuously ingests WAL from BigBrain for point-in-time recovery. Final destination for results files from Cisco and Hal. ZFS with snapshots.'
);

-- 5. NETGEAR M4300 — The Network Fabric
INSERT INTO items (
  title, description, price, rating, rating_count,
  asset_tag, serial_number, model_name, model_number, manufacturer,
  category_id, location_id, default_location_id, status, quantity,
  cpu_type, ram_amount, hard_drive_info, gpu, network_info, role, storage_detail,
  notes
) VALUES (
  'Netgear M4300-12X12F — Network Fabric Switch',
  E'High-Throughput Cluster Backplane.\n\nBonds physically separate machines into a single logical unit. The 40Gb/20Gb aggregations ensure that network bandwidth exceeds disk speed, guaranteeing that no CPU ever sits idle waiting for a file transfer.',
  3500.00, 5.0, 1,
  'NET-FABRIC-001', 'NGEAR-M4300-7AX', 'M4300-12X12F', 'XSM4324S', 'Netgear',
  11, 8, 8, 'available', 1,
  NULL, NULL, NULL, NULL,
  'Layer 2 Switching | Jumbo Frames MTU 9000 | Subnet: 192.168.100.x (Isolated)',
  'High-Throughput Cluster Backplane',
  NULL,
  '12x 10G SFP+ ports + 12x 10G Base-T ports. LACP bonding enabled. Isolated subnet with no internet access. Jumbo frames for max throughput.'
);
